name       : imagemagick
version    : 7.0.7_27
release    : 52
source     :
    - https://www.imagemagick.org/download/releases/ImageMagick-7.0.7-27.tar.xz : 543776f09d69e3ca29b1b83a9c0223185ba26bec673593840b4d7face6ea253b
license    : Apache-2.0
component  : multimedia.graphics
summary    : ImageMagick® suite to create, edit, compose, or convert bitmap images
patterns   :
    - devel : [/usr/share/man/man3]
    - docs : [/usr/share/doc]
description: |
    ImageMagick® is a software suite to create, edit, compose, or convert bitmap images. It can read and write images in a variety of formats (over 200) including PNG, JPEG, JPEG-2000, GIF, TIFF, DPX, EXR, WebP, Postscript, PDF, and SVG. Use ImageMagick to resize, flip, mirror, rotate, distort, shear and transform images, adjust image colors, apply various special effects, or draw text, lines, polygons, ellipses and Bézier curves.
builddeps  :
    - pkgconfig(autotrace)
    - pkgconfig(lcms2)
    - pkgconfig(liblzma)
    - pkgconfig(libopenjp2)
    - pkgconfig(libraw)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libwebp)
    - pkgconfig(OpenEXR)
    - pkgconfig(pangocairo)
    - bzip2-devel
setup      : |
    %configure --disable-static \
               --with-autotrace \
               --with-openjp2 \
               --with-perl \
               --with-rsvg
build      : |
    %make
install    : |
    %make_install
    privlib="%perl_privlib%"
    rm -rvf "$installdir/$privlib"
