name       : imagemagick
version    : 6.9.1
release    : 2
source     :
    - http://www.imagemagick.org/download/ImageMagick-6.9.1-10.tar.xz : 22565464059376513869b6626982e0726a33788ccc7e19a08e55ff1683d4ff92
license    : Apache-2.0
summary    : ImageMagick® suite to create, edit, compose, or convert bitmap images
patterns   :
    - docs: /usr/share/doc
description: |
    ImageMagick® is a software suite to create, edit, compose, or convert bitmap images. It can read and write images in a variety of formats (over 200) including PNG, JPEG, JPEG-2000, GIF, TIFF, DPX, EXR, WebP, Postscript, PDF, and SVG. Use ImageMagick to resize, flip, mirror, rotate, distort, shear and transform images, adjust image colors, apply various special effects, or draw text, lines, polygons, ellipses and Bézier curves.
builddeps  :
    - pkgconfig(zlib)
    - pkgconfig(autotrace)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(lcms2)
    - pkgconfig(liblzma)
    - pkgconfig(OpenEXR)
    - pkgconfig(pangocairo)
    - pkgconfig(libpng)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(cairo-svg)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libwebp)
    - pkgconfig(libtiff-4)
    - libjpeg-turbo-devel
setup      : |
    %configure --with-autotrace --with-perl --with-rsvg=yes --with-perl --disable-static
build      : |
    %make
install    : |
    %make_install
