name       : imagemagick
version    : 7.0.1_9
release    : 7
source     :
    - ftp://mirror.checkdomain.de/imagemagick/ImageMagick-7.0.1-9.tar.xz : 876cf76ce84657af5b1e28414d0c75911029ed3dd47c791e8a10d5c3f6014894
license    : Apache-2.0
component  : desktop.multimedia
summary    : ImageMagick® suite to create, edit, compose, or convert bitmap images
patterns   :
    - devel : [/usr/share/man/man3]
    - docs : /usr/share/doc
description: |
    ImageMagick® is a software suite to create, edit, compose, or convert bitmap images. It can read and write images in a variety of formats (over 200) including PNG, JPEG, JPEG-2000, GIF, TIFF, DPX, EXR, WebP, Postscript, PDF, and SVG. Use ImageMagick to resize, flip, mirror, rotate, distort, shear and transform images, adjust image colors, apply various special effects, or draw text, lines, polygons, ellipses and Bézier curves.
builddeps  :
    - pkgconfig(autotrace)
    - pkgconfig(cairo-svg)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(lcms2)
    - pkgconfig(liblzma)
    - pkgconfig(libpng)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libtiff-4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libwebp)
    - pkgconfig(OpenEXR)
    - pkgconfig(pangocairo)
    - pkgconfig(zlib)
    - libjpeg-turbo-devel
setup      : |
    %configure --with-autotrace --with-perl --with-rsvg=yes --with-perl --disable-static
build      : |
    %make
install    : |
    %make_install
    privlib="%perl_privlib%"
    rm -rvf "$installdir/$privlib"
