name       : imagemagick
version    : 7.0.10.2
release    : 139
source     :
    - https://imagemagick.org/download/ImageMagick-7.0.10-2.tar.xz : f22b72bd96c63233f23bfd21a3d9c70252bc9f388613117991e70669324a2305
license    : Apache-2.0
component  : multimedia.graphics
summary    : ImageMagick® suite to create, edit, compose, or convert bitmap images
patterns   :
    - devel : [/usr/share/man/man3]
    - docs : [/usr/share/doc]
description: |
    ImageMagick® is a software suite to create, edit, compose, or convert bitmap images. It can read and write images in a variety of formats (over 200) including PNG, JPEG, JPEG-2000, GIF, TIFF, DPX, EXR, WebP, Postscript, PDF, and SVG. Use ImageMagick to resize, flip, mirror, rotate, distort, shear and transform images, adjust image colors, apply various special effects, or draw text, lines, polygons, ellipses and Bézier curves.
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(lcms2)
    - pkgconfig(libheif)
    - pkgconfig(liblzma)
    - pkgconfig(libopenjp2)
    - pkgconfig(libraw)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libwebp)
    - pkgconfig(pangocairo)
    - bzip2-devel
setup      : |
    %configure --disable-static \
               --with-openjp2 \
               --with-perl \
               --with-rsvg
build      : |
    %make
install    : |
    %make_install
    privlib="%perl_privlib%"
    rm -rvf "$installdir/$privlib"

    # Use correct options for inkscape<1.0
    sed -e 's|--export-file|--export-png|' -i $installdir/etc/ImageMagick-7/delegates.xml
