name       : imagemagick
version    : 7.1.0_19
release    : 183
source     :
    - https://download.imagemagick.org/ImageMagick/download/releases/ImageMagick-7.1.0-19.tar.xz : 3fd79174ab0f30bc1643af3e654f1d2ffcc3a9554263981155688b4f49f7fd77
homepage   : https://imagemagick.org/
license    : Apache-2.0
component  : multimedia.graphics
summary    : ImageMagick® suite to create, edit, compose, or convert bitmap images
description: |
    ImageMagick® is a software suite to create, edit, compose, or convert bitmap images. It can read and write images in a variety of formats (over 200) including PNG, JPEG, JPEG-2000, GIF, TIFF, DPX, EXR, WebP, Postscript, PDF, and SVG. Use ImageMagick to resize, flip, mirror, rotate, distort, shear and transform images, adjust image colors, apply various special effects, or draw text, lines, polygons, ellipses and Bézier curves.
patterns   :
    - devel :
        - /usr/share/man/man3
    - docs :
        - /usr/share/doc
builddeps  :
    - pkgconfig(OpenEXR)
    - pkgconfig(ddjvuapi)
    - pkgconfig(fftw3)
    - pkgconfig(lcms2)
    - pkgconfig(libgvc)
    - pkgconfig(libheif)
    - pkgconfig(liblzma)
    - pkgconfig(libopenjp2)
    - pkgconfig(libraw)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libwebp)
    - pkgconfig(libzstd)
    - pkgconfig(pangocairo)
    - pkgconfig(raqm)
    - bzip2-devel
    - ghostscript-devel
setup      : |
    %patch -p1 < $pkgfiles/Stateless.patch
    %configure --disable-static \
               --enable-shared \
               --with-fftw \
               --with-gslib \
               --with-openjp2 \
               --with-perl \
               --with-rsvg
build      : |
    %make
install    : |
    %make_install
    install -dm00755 $installdir/usr/share/defaults
    mv $installdir/etc/ImageMagick-7 $installdir/usr/share/defaults
    rm -rvf "$installdir/%perl_privlib%"
    rmdir $installdir/etc
