name       : imagemagick
version    : 7.0.5_8
release    : 22
source     :
    - https://www.imagemagick.org/download/releases/ImageMagick-7.0.5-8.tar.xz : 007648793640b1d33f1285426df7c43fcf412eaef27b0b68fa7977bf29c4d30e
license    : Apache-2.0
component  : multimedia.graphics
summary    : ImageMagick® suite to create, edit, compose, or convert bitmap images
patterns   :
    - devel : [/usr/share/man/man3]
    - docs : /usr/share/doc
description: |
    ImageMagick® is a software suite to create, edit, compose, or convert bitmap images. It can read and write images in a variety of formats (over 200) including PNG, JPEG, JPEG-2000, GIF, TIFF, DPX, EXR, WebP, Postscript, PDF, and SVG. Use ImageMagick to resize, flip, mirror, rotate, distort, shear and transform images, adjust image colors, apply various special effects, or draw text, lines, polygons, ellipses and Bézier curves.
builddeps  :
    - pkgconfig(autotrace)
    - pkgconfig(cairo-svg)
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(lcms2)
    - pkgconfig(liblzma)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpng)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libtiff-4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(libwebp)
    - pkgconfig(OpenEXR)
    - pkgconfig(pangocairo)
    - pkgconfig(zlib)
    - libjpeg-turbo-devel
setup      : |
    %configure --with-autotrace --with-perl --with-rsvg=yes --with-perl --disable-static --with-openjp2
build      : |
    %make
install    : |
    %make_install
    privlib="%perl_privlib%"
    rm -rvf "$installdir/$privlib"
